repos:
  - repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
      - id: black
        language_version: python3.6
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.0.1
    hooks:
      - id: seed-isort-config
        language_version: python3.6

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
        language_version: python3.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: fix-encoding-pragma
