language: python
cache: pip
python:
  - "3.6"
dist: trusty
sudo: true
group: edge
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libuv0.10
install:
  - make install
jobs:
  include:
    - stage: test std asyncio
      script: make test
    - stage: test uvloop
      script: make uvtest
    - stage: test man
      script: make man
    - stage: test docs
      script: make docs
    - stage: deploy
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs/build
        on:
          branch: master
after_success:
  - make cov
  - codecov
