language: python
cache: pip
python:
  - "3.6"
dist: trusty
sudo: false
install:
  - make install
script:
  - make testall
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1ad06d2b30bf0712f90e
    on_success: always
    on_failure: always
    on_start: always
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build
  on:
    branch: master
