language: python
cache: pip
dist: xenial
sudo: false
group: travis_latest

install:
  - pip install codecov tox detox
script: tox
after_success:
  - tox -e coverage-report
  - codecov
deploy:
  - provider: script
    script: scripts/release.sh
    on:
      tags: true

env:
    global:
      - TWINE_USERNAME: kura
      # TWINE_PASSWORD:
      - secure: "Bd63ijidRb6vsEnMEDI1lUKNlSegrorisBttzXyucEisl0cu0FfahIuFoXmXL0NeTSpDKYb5HZoqC0J+7LXZep8ZkuV/8H/8j//J1ja3qCIsbfqqklNEYkfe0nO7uGyYkg/exLLZGqJVXeS5+xedPyW+LsDJ5XFYe/dMx6FAfZI="

matrix:
  fast_finish: true
  include:

  - python: '3.6'
    env: NAME=py36,py36-{setproctitle,uvloop}
    sudo: true
    before_install:
      - git clone https://github.com/libuv/libuv.git
      - pushd libuv/
      - git checkout $(git describe --tags)
      - sh autogen.sh
      - "./configure"
      - make
      - sudo make install
      - popd
    script:
      - tox -e py36
      - tox -e py36-setproctitle
      - tox -e py36-uvloop

  - python: '3.7'
    env: NAME=py37,py37-{setproctitle,uvloop}
    sudo: true
    before_install:
      - git clone https://github.com/libuv/libuv.git
      - pushd libuv/
      - git checkout $(git describe --tags)
      - sh autogen.sh
      - "./configure"
      - make
      - sudo make install
      - popd
    script:
      - tox -e py37
      - tox -e py37-setproctitle
      - tox -e py37-uvloop

  - python: "3.6"
    env: TOXENV=lint
  - python: '3.6'
    env: TOXENV=docs
    deploy:
      provider: pages
      skip_cleanup: true
      github_token:
        secure: "FGNxmBm5Zr2oLHK13HgqGKPFQKGrILvBUeC9F655V3hBTcOD9BXyeABwF0yvnGSS/1J/sQVNn71uRbZDfmxd/YTT8/5yK4yeuAiT1pnKcMppYaBA/691e9Uz9hB4yfivir/+ZWSlPMQJ2IiLvY6aBfJwwrNtiB5biWQiTlW+5aI="
      local_dir: .tox/docs/tmp/html
      on:
        branch: master
  - python: "3.6"
    env: TOXENV=build
  - python: "3.6"
    env: TOXENV=man
  - python: "3.6"
    env: TOXENV=pipfile
  - python: "3.6"
    env: TOXENV=setuppy
  - python: '3.6'
    env: TOXENV=shellcheck
    addons:
      apt:
        sources:
          - debian-sid
    before-script:
      - "sudo apt-get install cabal-install"
      - "cabal update"
      - "cabal install shellcheck"
