language: python
python:
  - "3.6"
install:
  - make install
script:
  - make test
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1ad06d2b30bf0712f90e
    on_success: always
    on_failure: always
    on_start: always
