language: python
cache: pip
dist: trusty
sudo: false
group: edge
install:
  - make install
after_success:
  - codecov
env:
    global:
      - TWINE_USERNAME: kura
      # TWINE_PASSWORD:
      - secure: "hNfTJGnWJKz2lfdF83P+GgO3EZowZYiJz9VrvenFt1IQLRaxPRBtnkzwNQmKpQ3rgkUU3VomU7mChQdx7bJhKjiL7sAkPnzRqzwooDfMFWJU828u/pIoH1WY1HqpiRQC8Q4iDKQhSFWy7zaGM95oR7otDd3dA85b1FbFAxegJV8="

matrix:
  fast_finish: true
  include:

  # cpython/asyncio (3.6)
  - python: '3.6'
    script: make test
    env: NAME="cpython/asyncio (3.6)"
    deploy:
      provider: script
      script: scripts/release.sh
      on:
        tags: true

  # cpython/uvloop (3.6)
  - python: '3.6'
    sudo: true
    env: NAME="cpython/uvloop (3.6)"
    before_install:
      - wget https://api.github.com/repos/libuv/libuv/tarball -O libuv.tar.gz
      - mkdir libuv
      - tar xvzf libuv.tar.gz -C libuv --strip-components 1
      - pushd libuv/
      - sh autogen.sh
      - "./configure"
      - make
      - sudo make install
      - popd
    install:
      - make install
      - pip install uvloop
    script: make test

  # docs (3.6)
  - python: '3.6'
    script: make docs
    env: NAME="docs (3.6)"
    deploy:
      provider: pages
      skip_cleanup: true
      github_token:
        secure: "FGNxmBm5Zr2oLHK13HgqGKPFQKGrILvBUeC9F655V3hBTcOD9BXyeABwF0yvnGSS/1J/sQVNn71uRbZDfmxd/YTT8/5yK4yeuAiT1pnKcMppYaBA/691e9Uz9hB4yfivir/+ZWSlPMQJ2IiLvY6aBfJwwrNtiB5biWQiTlW+5aI="
      local_dir: docs/build
      on:
        branch: master

  # man
  - install: skip
    env: NAME="man"
    script: make man

  # build sdist/wheel (3.6)
  - python: '3.6'
    install: skip
    env: NAME="build sdist/wheel (3.6)"
    script: make build

  # pipfile (3.6)
  - python: '3.6'
    install: skip
    env: NAME="pipfile (3.6)"
    script: make pipfile

  # shellcheck
  - language: generic
    env: NAME="shellcheck"
    install: skip
    addons:
      apt:
        sources:
          - debian-sid
        packages:
          - shellcheck
    script: make shellcheck
