language: python
python:
- '3.6'
cache: pip
dist: trusty
sudo: false
group: edge
install:
- make install
after_success:
- codecov
env:
    global:
        - TWINE_USERNAME: kura
        # TWINE_PASSWORD:
        - secure: "eHG6IOa71vyILd9M/09+z8zO9mcpSy12eNW2EIVJixuknDY+Q3othsHwYUP8p/T2rGyUGOzJkUdAArNtOQ3+MMUur4hnexcDmCntw/sNzJru2bl7AJR7m+sPZ4H35JBtLf68po4lS4qTRYfPbpmvWFzhWxJDCifOy5dq3BfeYN4="

matrix:
  fast_finish: true
  include:
  # asyncio
  - script: make test
    deploy:
      provider: script
      script: scripts/release.sh
      on:
        tags: true
  # uvloop
  - sudo: true
    before_install:
    - wget https://github.com/libuv/libuv/archive/v1.13.1.tar.gz -O libuv.tar.gz
    - tar xvzf libuv.tar.gz
    - pushd libuv-1.13.1/
    - sh autogen.sh
    - "./configure"
    - make
    - sudo make install
    - popd
    install:
    - make install
    - pip install uvloop
    script: make test
  # docs
  - script: make docs
    deploy:
      provider: pages
      skip_cleanup: true
      github_token:
        secure: "FGNxmBm5Zr2oLHK13HgqGKPFQKGrILvBUeC9F655V3hBTcOD9BXyeABwF0yvnGSS/1J/sQVNn71uRbZDfmxd/YTT8/5yK4yeuAiT1pnKcMppYaBA/691e9Uz9hB4yfivir/+ZWSlPMQJ2IiLvY6aBfJwwrNtiB5biWQiTlW+5aI="
      local_dir: docs/build
      on:
        branch: master
  # man
  - install: skip
    script: make man
  # build sdist/wheel
  - install: skip
    script: make build
  # pipfile
  - install: skip
    script: make pipfile
