language: python
cache: pip
python:
  - "3.6"
  - "3.7-dev"
dist: trusty
sudo: false
install:
  - make install
script:
  - make test
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1ad06d2b30bf0712f90e
    on_success: always
    on_failure: always
    on_start: always
