language: python
cache: pip
dist: xenial
sudo: false
group: travis_latest

install:
  - pip install codecov tox detox
script: tox
after_success:
  - tox -e coverage-report
  - codecov

matrix:
  fast_finish: true
  include:

  - python: '3.6'
    env: TOXENV=py36
